import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
const here = path.dirname(fileURLToPath(import.meta.url));
const dnaRoot = path.resolve(here,'..');
const [,, artifactArg, sidecarArg] = process.argv;
if (!artifactArg || !sidecarArg) throw new Error('artifact and sidecar are required');
const artifact = path.resolve(process.cwd(),artifactArg);
const sidecar = path.resolve(process.cwd(),sidecarArg);
const genomeBytes=fs.readFileSync(path.join(dnaRoot,'genome','omega-dna.json'));
const genome=JSON.parse(genomeBytes);
const genomeHash=crypto.createHash('sha256').update(genomeBytes).digest('hex');
const artifactHash=crypto.createHash('sha256').update(fs.readFileSync(artifact)).digest('hex');
const m=JSON.parse(fs.readFileSync(sidecar,'utf8'));
const fail=[];
if(m.dna?.genome_id!==genome.genome_id) fail.push('GENOME_ID_MISMATCH');
if(m.dna?.genome_version!==genome.genome_version) fail.push('GENOME_VERSION_MISMATCH');
if(m.dna?.genome_sha256!==genomeHash) fail.push('GENOME_HASH_MISMATCH');
if(m.artifact_sha256!==artifactHash) fail.push('ARTIFACT_HASH_MISMATCH');
if(!m.parent?.id) fail.push('PARENT_MISSING');
if(!Array.isArray(m.applied_profiles)) fail.push('PROFILES_MISSING');
if(!Array.isArray(m.evidence_refs) || m.evidence_refs.length===0) fail.push('EVIDENCE_MISSING');
if(m.gate?.result!=='PASS') fail.push('GATE_NOT_PASS');
if(m.gate?.tested_equals_delivered!==true) fail.push('TESTED_DELIVERED_NOT_PROVEN');
const forbidden=new Set(genome.claims_forbidden_without_specific_evidence||[]);
for(const c of (m.claims||[])) if(forbidden.has(c)&&m.gate?.scope!=='FIELD_AS_PROVEN') fail.push(`FORBIDDEN_CLAIM:${c}`);
if(fail.length){console.error(JSON.stringify({status:'NO_GO',failures:fail},null,2));process.exit(1)}
console.log(JSON.stringify({status:'PASS',artifact_sha256:artifactHash,genome_sha256:genomeHash},null,2));
